# Site settings
author: Hannah Angle
title: Studying Software Engineering
header-img: img/home-bg.png
email: hannahcangle@gmail.com
copyright_name: Hannah Angle
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering Student
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Hcangle

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
